### ISSUE TITLE
自动获取最新frp版本号

### ISSUE THREAD

**Issue by onepve** [clangcn/onekey-install-shell#16]
version.sh
```
frpver=$(wget -qO- https://github.com/fatedier/frp/releases/latest | grep "<title>" |sed -r 's/.*Release (.+) · fatedier.*/\1/')
export FRPS_VER=${frpver:1}
```
即可.安装选择github

**Comment by snowdream** [comment]
麻烦更新一下，自动获取版本号。

**Comment by tufu9441** [comment]
作者好像不打算继续维护了？😂

**Comment by bajins** [comment]
> 作者好像不打算继续维护了？😂

https://github.com/dylanbai8/frpspro

**Comment by bajins** [comment]
> version.sh
> 
> ```
> frpver=$(wget -qO- https://github.com/fatedier/frp/releases/latest | grep "<title>" |sed -r 's/.*Release (.+) · fatedier.*/\1/')
> export FRPS_VER=${frpver:1}
> ```
> 
> 即可.安装选择github
```bash
curl -s https://api.github.com/repos/fatedier/frp/releases/latest --connect-timeout 10| grep 'tag_name' | cut -d\" -f4
```

**Comment by tufu9441** [comment]
https://github.com/MvsCode/frp-onekey
