### ISSUE TITLE
Frp 版本已更新到 0.17

### ISSUE THREAD

**Issue by kasuganosoras** [clangcn/onekey-install-shell#5]
版本已经更新了，但是脚本里检测到的最新版本还是0.16.1

**Comment by tufu9441** [comment]
同样发现了，貌似脚本的更新功能并不能直接检测出frp官方最新的release，版本号是在脚本中预先设定好的。

**Comment by tufu9441** [comment]
已经更新到0.18.0了

**Comment by tufu9441** [comment]
每次frp更新后，都需要脚本这边也同步做出修改才能检测到新版本吗？目前frp最新版是0.19.0，但是脚本检测出remote version依然是0.18.0
